name: GH Upload Release Asset On Release Publish

on:
  release:
    types: [published]
    branches:
      - '*'

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build Release Asset
        run: |
          rsync -Rr --exclude=".*" . ./Greetings
          zip -r Greetings_${{ github.ref_name }}.zip Greetings
          rm -r Greetings
      - name: View Release Asset
        run: |
          unzip -l Greetings_${{ github.ref_name }}.zip
      - name: Upload Release Asset
        id: upload_release_asset
        uses: softprops/action-gh-release@v2
        with:
          files: Greetings_${{ github.ref_name }}.zip
      - name: Release Output
        run: echo "💡 Release available in ${{ steps.upload_release_asset.outputs.url }}"
      - name: Uploaded Release Assets Output
        run: echo "💡 Assets available ${{ steps.upload_release_asset.outputs.assets }}"
